
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action SettingAction;
	
	private global::Gtk.Action LoginAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Entry entryPost;
	
	private global::Gtk.Button buttonPost;
	
	private global::Gtk.Button buttonRefresh;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.TreeView treeviewMain;
	
	private global::Gtk.Statusbar statusbarMain;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.SettingAction = new global::Gtk.Action ("SettingAction", global::Mono.Unix.Catalog.GetString ("Setting"), null, null);
		this.SettingAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Setting");
		w1.Add (this.SettingAction, null);
		this.LoginAction = new global::Gtk.Action ("LoginAction", global::Mono.Unix.Catalog.GetString ("Login"), null, null);
		this.LoginAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Login");
		w1.Add (this.LoginAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Nabeyaki");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='SettingAction' action='SettingAction'><menuitem name='LoginAction' action='LoginAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entryPost = new global::Gtk.Entry ();
		this.entryPost.CanFocus = true;
		this.entryPost.Name = "entryPost";
		this.entryPost.IsEditable = true;
		this.entryPost.InvisibleChar = '•';
		this.hbox1.Add (this.entryPost);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryPost]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonPost = new global::Gtk.Button ();
		this.buttonPost.CanFocus = true;
		this.buttonPost.Name = "buttonPost";
		this.buttonPost.UseUnderline = true;
		this.buttonPost.Label = global::Mono.Unix.Catalog.GetString ("Post");
		global::Gtk.Image w4 = new global::Gtk.Image ();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.buttonPost.Image = w4;
		this.hbox1.Add (this.buttonPost);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonPost]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonRefresh = new global::Gtk.Button ();
		this.buttonRefresh.CanFocus = true;
		this.buttonRefresh.Name = "buttonRefresh";
		this.buttonRefresh.UseUnderline = true;
		this.buttonRefresh.Label = global::Mono.Unix.Catalog.GetString ("Refresh");
		global::Gtk.Image w6 = new global::Gtk.Image ();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
		this.buttonRefresh.Image = w6;
		this.hbox1.Add (this.buttonRefresh);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonRefresh]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeviewMain = new global::Gtk.TreeView ();
		this.treeviewMain.CanFocus = true;
		this.treeviewMain.Name = "treeviewMain";
		this.GtkScrolledWindow1.Add (this.treeviewMain);
		this.vbox1.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow1]));
		w10.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbarMain = new global::Gtk.Statusbar ();
		this.statusbarMain.Name = "statusbarMain";
		this.statusbarMain.Spacing = 6;
		this.vbox1.Add (this.statusbarMain);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbarMain]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 854;
		this.DefaultHeight = 598;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.LoginAction.Activated += new global::System.EventHandler (this.OnClickLogin);
		this.buttonPost.Clicked += new global::System.EventHandler (this.OnClickPost);
		this.buttonRefresh.Clicked += new global::System.EventHandler (this.OnClickRefresh);
	}
}
